import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faSearch,
  faTimes,
  faBell,
  faExpandArrowsAlt,
  faThLarge,
  faTachometerAlt,
  faAngleLeft,
  faEnvelope,
  faLock,
  faUser,
  faTh,
  faCopy,
  faChartPie,
  faTree,
  faEdit,
  faTable,
  faCalendarAlt,
  faImage,
  faColumns,
  faShoppingCart,
  faArrowCircleRight,
  faChartBar,
  faUserPlus,
    faSyncAlt,
    faPlus
} from "@fortawesome/free-solid-svg-icons";
import { faFacebook, faGooglePlus } from "@fortawesome/free-brands-svg-icons";
import {
  faCircle,
  faFlag,
  faStar,
  faEnvelope as farEnvelope,
  faCopy as farCopy,
  faBookmark,
  faThumbsUp,
  faCalendar,
  faComments,
} from "@fortawesome/free-regular-svg-icons";
library.add(
  faSearch,
  faThLarge,
  faExpandArrowsAlt,
  faBell,
  faTimes,
  faBars,
  faTachometerAlt,
  faAngleLeft,
  faEnvelope,
  faLock,
  faFacebook,
  faGooglePlus,
  faUser,
  faCircle,
  faTh,
  faCopy,
  faChartPie,
  faTree,
  faEdit,
  faTable,
  faCalendarAlt,
  faImage,
  faColumns,
  faFlag,
  faStar,
  farEnvelope,
  farCopy,
  faBookmark,
  faThumbsUp,
  faCalendar,
  faComments,
  faShoppingCart,
  faArrowCircleRight,
  faChartBar,
  faUserPlus,
    faSyncAlt,
    faPlus
);
